# Generated by Django 3.1 on 2020-09-16 02:45

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0004_auto_20200906_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchedvalue',
            name='yearmodel',
            field=django_mysql.models.ListTextField(models.CharField(blank=True, max_length=100, null=True), default='', size=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='searchedvalue',
            name='mileagerange',
            field=django_mysql.models.ListTextField(models.CharField(max_length=100), size=100),
        ),
        migrations.AlterField(
            model_name='searchedvalue',
            name='pricerange',
            field=django_mysql.models.ListTextField(models.CharField(max_length=100), size=100),
        ),
    ]
