# Generated by Django 3.1 on 2020-09-16 02:45

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0005_auto_20200916_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchedvalue',
            name='yearmodel',
            field=django_mysql.models.ListTextField(models.CharField(max_length=100), size=100),
        ),
    ]
